//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [MetadataType(typeof(ToValidateName))]
    public partial class Campaign
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Client { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Type { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public DateTime? StartDate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public DateTime? EndDate { get; set; }
    }

    class ToValidateName
    {
        [Remote("IsCampaignExists", "Campaign", ErrorMessage = "Campaign Name already exists")]
        public string Name { get; set; }
    }
}
